### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by bahadorian** [pkestene/xsmurf#4]
The readme file suggests excecuteing the following line for configureing:
./configure --with-tcl=/usr/lib/tcl8.5 --with-tk=/usr/lib/tk8.5 --with-hdf5=no

However, the "configure" file does not exist. Is there another step before this one for building this file?

**Comment by ogadaki** [comment]
I guess you can execute `autoconf` as a first step to generate the `configure` file. It is the classic way to do it. But I haven't try it recently for this project.

**Comment by pkestene** [comment]
yes exactly, right after cloning, you execute
```shell
./bootstrap.sh
```
This will run autoconf for you, and generate file configure.
I modified README.md to mention this preliminary step.

**Comment by bahadorian** [comment]
Thank you!
Now I get the configure file. However, the output of executing `./bootstrap.sh` ends with the following lines:
```
interpreter/Makefile.am:3: error: HDF5_CPPFLAGS must be set with '=' before using '+='
autoreconf: automake failed with exit status: 1
```
and accordingly, the configure doesn't work.

**Comment by pkestene** [comment]
It's working on my side using a fresh clone of the project.

It probably means you're working on a platform where HDF5 library is not installed.
But it also means that there is bug in the way we detect for HDF5 flags in xsmurf, because it was supposed to work on a system where hdf5 is not installed !

If you have the possibility to install hdf5 library (there surely is a deb or rpm package on your linux distro), go for it. Meanwhile I'll try to fix the build system so that it doesn't show up again.

Sorry for the inconvenience.

**Comment by pkestene** [comment]
Wait, I was wrong above.
Since the problem appends already at autoreconf time, I suspect that the m4 macro  ax_lib_hdf5 is not found.

This macro is provided by package autoconf-archive on debian-like system. This can be fixed by
```shell
sudo apt install autoconf-archive
```

then run bootstrap.sh again. It should be fine.

The m4 macro ax_lib_hdf5 is responsible for initalizing flags like HDF5_CPPFLAGS; the error message you have means the flag does not already exist (that's why += is not allowed), hence the macro was not executed.

I hope this helps.

**Comment by bahadorian** [comment]
Thank you so much!
Now `bootstrap.sh` runs perfectly well, but still executing `make` results in the following error:
```
  CC       image_cmds.lo
image_cmds.c:28:10: fatal error: netcdf.h: No such file or directory
 #include <netcdf.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:528: recipe for target 'image_cmds.lo' failed
make[1]: *** [image_cmds.lo] Error 1
make[1]: Leaving directory '/home/mohammad/Documents/xsmurf-master/interpreter'
Makefile:530: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by pkestene** [comment]
2 possibilities :
- rerun configure with option '--with-netcdf4=no' to tell xsmurf build system no to use netcdf IO library
- install package libnetcdf-dev to have netcdf IO on your system

**Comment by bahadorian** [comment]
I installed `libnetcdf-dev` and executed `make` successfully.

now trying to execute `./main/xsmurf, I get this blank window
![Screenshot from 2020-02-01 18-21-59](https://user-images.githubusercontent.com/52409527/73596145-0138ef80-4520-11ea-9e4e-66ceadb6cbec.png)
is this alright?

**Comment by pkestene** [comment]
No this is not ok, but you are just one step away from getting it right; there is a resource file in dir main/smurfrc, just copy it into your home and rename it to .smurfrc.
```shell
cp ./main/smurfrc ~/.smurfrc
```
It should be finally ok. I'm sorry you had to go through all this steps.

**Comment by bahadorian** [comment]
Thank you so much!
Now, It works perfectly fine and gives correct results to the templates.
